Solving typo error
  1) FizzBuzz#play returns 1 when 1 is given
     Failure/Error: number % divisor == 1

     NameError:
       undefined local variable or method `divisor' for #<FizzBuzz:0x00007fb0958122f0>
       Did you mean?  divis0r
     # ./lib/fizzbuzz.rb:12:in `is_divisible_by?'
     # ./lib/fizzbuzz.rb:4:in `play'
     # ./spec/fizzbuzz_spec.rb:6:in `block (3 levels) in <top (required)>'