Bug in the code error fixed: error below
  1) FizzBuzz#play returns 1 when 1 is given
     Failure/Error: string << "Fizz" if is_divisible_by?(3, the_number)

     NameError:
       undefined local variable or method `the_number' for #<FizzBuzz:0x00007fdbe087f988>
     # ./lib/fizzbuzz.rb:4:in `play'
     # ./spec/fizzbuzz_spec.rb:6:in `block (3 levels) in <top (required)>'